### ISSUE TITLE
Crewmate Switcher resolves to IPv6 address 

### ISSUE THREAD

**Issue by EliasHolzmann** [NaokiStark/Crewmate-switcher#3]
When entering a domain name that has a IPv6 address as well as a IPv4 address associated with it, Crewmate Switcher seems to prefer the IPv6 address. It writes this address – with length 8 bytes instead of 4 – into the regionInfo.dat. The Among Us client does not support this.

Example of a IPv6 address inside a (censored) regionInfo.dat:

    00000000  00 00 00 00 08 49 6d 70  6f 73 74 6f 72 25 32 30  |.....Impostor%20|
    00000010  30 33 3a 64 61 3a 61 37  31 30 3a 38 30 30 30 3a  |03:da:a710:8000:|
    00000020  xx xx xx xx xx xx xx xx  xx xx xx xx xx xx xx xx  |xxxx:xxxx:xxxx:x|
    00000030  xx xx xx 01 00 00 00 11  49 6d 70 6f 73 74 6f 72  |xxx.....Impostor|
    00000040  2d 4d 61 73 74 65 72 2d  31 20 03 00 da a7 10 80  |-Master-1 ......|
    00000050  00 xx xx xx xx xx xx xx  xx 07 56 00 00 00 00     |..........V....|

**Comment by NaokiStark** [comment]
> https://github.com/NaokiStark/Crewmate-switcher/commit/5e36072ceb6aeb98658793445697d66efdc6cd21

**Comment by Nekitaw** [comment]
> https://github.com/NaokiStark/Crewmate-switcher/commit/28a048d1ae21530af9978a580e22efbdaad78994

**Comment by EliasHolzmann** [comment]
Thanks, but this doesn't work for me. For example, when entering google.com as the host name (they have both IPv6 and IPv4 addresses):

```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: pw.fabi.crewmate, PID: 24015
    java.lang.ClassCastException: java.net.Inet6Address cannot be cast to java.net.Inet4Address
        at pw.fabi.crewmate.IPHandler.getIp(IPHandler.java:21)
        at pw.fabi.crewmate.MainActivity.lambda$onCreate$0$MainActivity(MainActivity.java:48)
        at pw.fabi.crewmate.-$$Lambda$MainActivity$PfnjwimloGAK3OWvJVFJ80UH6RU.onClick(Unknown Source:2)
        at android.view.View.performClick(View.java:7259)
        at com.google.android.material.button.MaterialButton.performClick(MaterialButton.java:967)
        at android.view.View.performClickInternal(View.java:7236)
        at android.view.View.access$3600(View.java:801)
        at android.view.View$PerformClick.run(View.java:27896)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7397)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:935)
```

I haven't worked on an Android app in years, but I will have a look at this and create a pull request if I am successful.

**Comment by Nekitaw** [comment]
Thank you

**Comment by EliasHolzmann** [comment]
You're welcome, thanks for merging!
